version: '3.4'

services:
  telegrambotlggoogledrive:
    image: telegrambotlggoogledrive
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./sa.json:/app/sa.json
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    environment:
      - TELEGRAM_API_TOKEN
      - LOCATION_IQ_API_TOKEN

