version: '3.4'

services:
  telegram-bot-google-drive:
    image: telegram-bot-google-drive
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config:/app/config
    environment:
      - TELEGRAM_API_TOKEN
      - LOCATION_IQ_API_TOKEN

