version: '3.4'

services:
  telegrambotlggoogledrive:
    image: telegrambotlggoogledrive
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

